### ISSUE TITLE
How to run the demo?

### ISSUE THREAD

**Issue by johncblacker** [entityframeworktutorial/EF6-DBFirst-Demo#10]
I did a build, then got an exception...copied in next comment.

**Comment by johncblacker** [comment]
Sorry for the previous post...I was pointing to the wrong repository/demo.  Anywya, I did get it to run with most working except an exception:
Unhandled Exception: System.InvalidOperationException: Spatial types and functions are not available for this provider because the assembly 'Microsoft.SqlServer.Types' version 10 or higher could not be found.
   at System.Data.Entity.SqlServer.SqlTypesAssemblyLoader.GetSqlTypesAssembly()
   at System.Data.Entity.SqlServer.SqlSpatialServices.GeographyFromText(String wellKnownText)
   at System.Data.Entity.Spatial.DbGeography.FromText(String wellKnownText)
   at EF6DBFirstDemo.Program.SpatialDataType() in C:\Users\jblac\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\EF6-DBFirst-Demo\EF6DBFirstDemo\Program.cs:line 308
   at EF6DBFirstDemo.Program.Main(String[] args) in C:\Users\jblac\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\EF6-DBFirst-Demo\EF6DBFirstDemo\Program.cs:line 25

which is the "SpatialDataType(); line in program.cs...however, it at least got that far.
